---
- name: Check existence of Browserless systemd service
  ansible.builtin.stat:
    path: "{{ sysd_docker_service_path }}/{{ browserless_identifier }}.service"
  register: browserless_service_stat

- name: Uninstall Browserless systemd services and files
  when: browserless_service_stat.stat.exists | bool
  block:
    - name: Ensure Browserless systemd service is stopped
      ansible.builtin.service:
        name: "{{ browserless_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Browserless systemd service does not exist
      ansible.builtin.file:
        path: "{{ sysd_docker_service_path }}/{{ browserless_identifier }}.service"
        state: absent

    - name: Ensure Browserless container network does not exist via community.docker.docker_network
      when: sysd_docker_net_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ browserless_container_network }}"
        state: absent

    - name: Ensure Browserless container network does not exist via ansible.builtin.command
      when: sysd_docker_net_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ sysd_docker_host_command }} network rm
          {{ browserless_container_network }}
      register: network_deletion_result
      changed_when: browserless_container_network in network_deletion_result.stdout

    - name: Ensure Browserless path does not exist
      ansible.builtin.file:
        path: "{{ browserless_base_path }}"
        state: absent
